site_name: "QUADS"
site_author: Nihad Nagi
site_description: Description
site_url: https://nihads-nagis.github.io/9999/
docs_dir: docs

theme:
  name: material
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    # - navigation.top
    - toc.follow
    # - navigation.tabs
    # - toc.integrate
    - navigation.footer
  palette:
    - scheme: slate
      # primary: deep purple
      primary: deep purple
      accent: pink
      # toggle:
        # icon: material/weather-sunny
        # name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      theory: material/atom
      concept: material/lightbulb-outline
      timeline: material/timeline
extra:
  alternate:
    - name: English
      link: /9999/en
      lang: en
    - name: 中文
      link: /9999/zh/
      lang: zh
plugins:
  # - search
  - include-markdown:
      comments: true
  # - i18n:
  #     languages:
  #       - locale: en
  #         name: English
  #         build: true
  #         default: true
  #       - locale: zh
  #         name: 中文
  #         build: true

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - tables
  - fenced_code
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 4

nav:
  - Home: index.md

extra_css:
  - assets/stylesheets/always-show-toc.css
  # - styles/main.css
  - assets/stylesheets/cards.css
extra_javascript:
  - https://unpkg.com/mermaid@11/dist/mermaid.min.js
  # - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
  - assets/javascripts/init-mermaid.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - assets/javascripts/go.js
  # - assets/javascripts/gojs-filter.js
  # - assets/javascripts/gojs-init.js
watch:
  - docs
