site_name: "QUADS"
site_author: Nihad Nagi
site_description: Description
site_url: https://nihads-nagis.github.io/9999/
docs_dir: docs

theme:
  name: material
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    # - navigation.top
    - toc.follow
    - navigation.tabs
    - toc.integrate
    - navigation.footer
  palette:
    - scheme: default
      primary: blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

extra:
  alternate:
    - name: English
      link: /9999/en
      lang: en
    - name: 中文
      link: /9999/zh/
      lang: zh


plugins:
  # - search
  - include-markdown:
      comments: true
  # - i18n:
  #     languages:
  #       - locale: en
  #         name: English
  #         build: true
  #         default: true
  #       - locale: zh
  #         name: 中文
  #         build: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - fenced_code
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: en/index.md