site_name: "QUADS"
site_author: Nihad Nagi
site_url: https://nihads-nagis.github.io/9999/
site_description: Description
docs_dir: docs
theme:
  name: material
  palette:
    scheme: dracula
    primary: deep purple
    accent: deep purple
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.follow
plugins:
  - search
  - mkdocs_pymdownx_material_extras
  - include-markdown:
      comments: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - tables
  - fenced_code
  - toc:
      permalink: true
      toc_depth: 3
nav:
  - Home: index.md
  - Guide: guide.md
