site_name: "QUADS"
site_author: Nihad Nagi
site_description: Description
site_url: https://nihads-nagis.github.io/9999/
docs_dir: docs

theme:
  name: material
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    # - navigation.top
    - toc.follow
    # - navigation.tabs
    # - toc.integrate
    - navigation.footer
  palette:
    - scheme: slate
      # primary: deep purple
      primary: deep purple
      accent: pink
      # toggle:
        # icon: material/weather-sunny
        # name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition:
      theory: material/atom
      concept: material/lightbulb-outline
      timeline: material/timeline
extra:
  alternate:
    - name: English
      link: /9999/en
      lang: en
    - name: 中文
      link: /9999/zh/
      lang: zh


plugins:
  # - search
  - include-markdown:
      comments: true
  # - i18n:
  #     languages:
  #       - locale: en
  #         name: English
  #         build: true
  #         default: true
  #       - locale: zh
  #         name: 中文
  #         build: true

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - fenced_code
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: en/index.md

extra_css:
  - styles/always-show-toc.css
  # - styles/main.css
  - styles/cards.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
